# Copyright The MarinFold Authors
# SPDX-License-Identifier: Apache-2.0

"""Assemble the GitHub Pages site from the experiment dashboards.

Pages used to publish the repository root, which meant the whole 256 MB tree —
every experiment's committed data — went to the builder on every push, and the
legacy builder never finished. Only a handful of directories are actually meant
to be browsed, so this copies those into ``_site/`` and leaves the rest alone.

What gets published:

* every ``experiments/*/dashboard/`` directory that has an ``index.html``, at
  the same path it has in the repository, so links already handed out keep
  working;
* a generated landing page listing them.

Adding a dashboard to the site means adding an ``index.html`` under a
``dashboard/`` directory in the experiment — nothing here needs editing.

    uv run python scripts/build_pages_site.py --out _site
"""

import argparse
import html
import re
import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
EXPERIMENTS = REPO / "experiments"

#: Pulled out of each experiment's README frontmatter for the landing page.
TITLE = re.compile(r"^\s*title:\s*(.+?)\s*$", re.MULTILINE)
ISSUE = re.compile(r"^\s*issue:\s*(\d+)\s*$", re.MULTILINE)

PAGE = """<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>MarinFold — evaluation dashboards</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{
    margin: 0 auto; padding: 40px 24px; max-width: 70ch; line-height: 1.55;
    font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  }}
  h1 {{ font-size: 22px; margin: 0 0 6px; }}
  p.lede {{ color: #666; margin: 0 0 28px; }}
  ul {{ list-style: none; padding: 0; }}
  li {{ padding: 14px 0; border-top: 1px solid #8883; }}
  a {{ text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .meta {{ color: #666; font-size: 13px; }}
</style>
<h1>MarinFold — evaluation dashboards</h1>
<p class="lede">Interactive pages published from
<a href="https://github.com/Open-Athena/MarinFold">Open-Athena/MarinFold</a>.
Each one is generated by the experiment it belongs to.</p>
<ul>
{items}
</ul>
"""

ITEM = """  <li>
    <a href="{href}"><b>{name}</b></a>
    <div class="meta">{title}</div>
    <div class="meta">{experiment}{issue}</div>
  </li>"""


def dashboards() -> list[Path]:
    """Every experiment dashboard directory with a page in it."""

    return sorted(
        path.parent
        for path in EXPERIMENTS.glob("*/dashboard/index.html")
    )


def describe(experiment: Path) -> tuple[str, str]:
    """The experiment's title and issue number, from its README frontmatter."""

    readme = experiment / "README.md"
    if not readme.exists():
        return "", ""
    text = readme.read_text(errors="replace")[:4000]
    title = TITLE.search(text)
    issue = ISSUE.search(text)
    return (
        (title.group(1).strip("'\"") if title else ""),
        (issue.group(1) if issue else ""),
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=str(REPO / "_site"))
    arguments = parser.parse_args()
    out = Path(arguments.out)
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    items = []
    for dashboard in dashboards():
        experiment = dashboard.parent
        relative = dashboard.relative_to(REPO)
        shutil.copytree(dashboard, out / relative)
        title, issue = describe(experiment)
        items.append(
            ITEM.format(
                href=f"{relative}/index.html",
                name=html.escape(experiment.name),
                title=html.escape(title),
                experiment=html.escape(str(experiment.relative_to(REPO))),
                issue=(
                    f' · <a href="https://github.com/Open-Athena/MarinFold/issues/{issue}">#{issue}</a>'
                    if issue
                    else ""
                ),
            )
        )
        print(f"[site] {relative}", flush=True)

    (out / "index.html").write_text(PAGE.format(items="\n".join(items)))
    # Belt and braces: the Actions deployer serves the artifact verbatim, but a
    # .nojekyll costs nothing and keeps behaviour identical if the source is
    # ever switched back to a branch.
    (out / ".nojekyll").write_text("")

    total = sum(path.stat().st_size for path in out.rglob("*") if path.is_file())
    print(f"{len(items)} dashboard(s), {total / 1e6:.1f} MB -> {out}")
    if not items:
        raise SystemExit("no dashboards found; refusing to publish an empty site")


if __name__ == "__main__":
    main()
